name: Publish npm package

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # Persist Git credentials for later steps

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@bineeshn'

      - name: Install dependencies
        run: npm install

      - name: Determine version bump
        id: version
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          if [[ $PR_TITLE == *"major"* ]]; then
            echo "BUMP=major" >> $GITHUB_OUTPUT
          elif [[ $PR_TITLE == *"minor"* ]]; then
            echo "BUMP=minor" >> $GITHUB_OUTPUT
          else
            echo "BUMP=patch" >> $GITHUB_OUTPUT
          fi

      - name: Bump version
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          npm version ${{ steps.version.outputs.BUMP }}

      - name: Push version commit and tag
        run: |
          git push origin main
          git push --tags

      - name: Build package
        run: npm run rollup

      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GIT_PACKAGE }}