# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish npm package

on:
  pull_request:
    types:
      - opened
      - synchronize  # Triggered when new commits are pushed to the PR
    branches:
      - main
  pull_request_target:
    types:
      - closed
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  publish:
    if: github.event.pull_request.merged == true
    needs: test  # Ensure the publish job only runs if the test job succeeds
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.FINE_GIT }}
          persist-credentials: true  # Persist credentials for later steps

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@armadasystems'

      - name: Install dependencies
        run: npm install

      - name: Determine version bump
        id: version
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          if [[ $PR_TITLE == *"major"* ]]; then
            echo "BUMP=major" >> $GITHUB_OUTPUT
          elif [[ $PR_TITLE == *"minor"* ]]; then
            echo "BUMP=minor" >> $GITHUB_OUTPUT
          else
            echo "BUMP=patch" >> $GITHUB_OUTPUT
          fi

      - name: Bump version
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          npm version ${{ steps.version.outputs.BUMP }}

      - name: Push version commit and tag
        run: |
          git push origin main
          git push --tags

      - name: Build package
        run: npm run rollup

      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.FINE_GIT }}